[package]
name = "huginn"
version = "0.1.0"
edition = "2021"

[dependencies]
auto_ops = "0.3.0"
log = "0.4.22"
rand = "0.9.0-alpha.2"

[features]
double-precision = ["double-precision-float", "double-precision-int"]
double-precision-float = []
double-precision-int = []